[package]
name = "lightracer"
version = "0.1.0"
authors = ["Greg Cowan <cowang4@yahoo.com>"]
edition = "2018"

[dependencies]
enum_dispatch = "0.1"
image = "0.19"
serde = "1.0"
serde_derive = "1.0"

[profile.release]
debug = true
